### ISSUE TITLE
swaggerhubUpload task doesn't download resolved yaml/json

### ISSUE THREAD

**Issue by rakeshprajapati1982** [swagger-api/swaggerhub-gradle-plugin#15]
I have written api spec on swaggerhub which refers some common domains defined within myorg. See example below.

```yaml
components:
  headers:
    x-correlation-id:
      description: Unique correlation ID auto generated for server for each api call.
      required: true
      schema:
        $ref: 'https://api.swaggerhub.com/domains/myorg/CommonComponents/1.0.0#/components/schemas/x-correlation-id'    
```

When I download the api spec yaml using swaggerhubDownload gradle task, it doesn't resolve the reference. It just downloads it as is which is not in good to feed to next task in my workflow for codegen.

**Suggestion**
I looked up swaggerhub documentation and there is option to download resolved api spec by passing a query parameter `resolved=true`. Reference https://support.smartbear.com/swaggerhub/docs/apis/downloading-swagger-definition.html

I tried using this query param in postman and it works.

Can we add resolved as a parameter to the `swaggerhubDownload` task?
